### ISSUE TITLE
Capacitor Configuration

### ISSUE THREAD

**Issue by NoelBaron** [braze-inc/braze-cordova-sdk#95]
Hey there, 

Do you have guidance for configuring the SDK with capacitor? I've added the plugin with cap sync, but it's unclear how to properly initialize the API Key and API url values.

With capacitor we have:
- `capacitor.config.ts` for plugin configuration
- Info.plist (ios) and `AndroidManifest.xml`

**Comment by NoelBaron** [comment]
For those wondering: 
```
// capacitor.config.ts
cordova: {
    preferences: {
      "com.appboy.api_key": "[API KEY HERE]",
      "com.appboy.ios_api_endpoint": "[ENDPOINT HERE]",
    },
 }
```

**Comment by jerielng** [comment]
Hey @NoelBaron, you can refer to this [page](https://www.braze.com/docs/developer_guide/platform_integration_guides/cordova/initial_setup/customizations) for the full list of configurations available in this SDK. We would first recommend changing any instances of `appboy` to `braze` as that namespace is no longer being used or recognized. If that does not resolve your issue, please write into support@braze.com and reference this GitHub issue.

Note that support would be limited since Capacitor is not an officially supported integration method, although we have had reports of other users successfully integrating in the past. If you would like to raise signal for official Capacitor support, please submit some product feedback [here](https://dashboard.braze.com/resources/roadmap)!
